// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmamovbizsoslscjbvzj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tYW1vdmJpenNvc2xzY2pidnpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Mjc5MzYsImV4cCI6MjA3MTIwMzkzNn0.q_LJ-Foy_Q3Jsn1zXQv1y4gs1NLL-qlEPBhFgQrwo8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});